### ISSUE TITLE
Import Error when using napalm Aruba driver

### ISSUE THREAD

**Issue by Profecy** [napalm-automation-community/napalm-aruba-cx#17]
Hi,
I currently am experiencing a problem when trying to use the Aruba driver for napalm...

When i use the following command:
napalm --vendor aoscx --user <username> --password <pw_redacted> <hostname here> call get_facts

Napalm errors out wit the following message:

2021-07-07 11:43:54,370 - napalm - ERROR - get_network_driver - Failed: cannot import name 'system'

================= Traceback =================

Traceback (most recent call last):
  File "/opt/netbox/venv/bin/napalm", line 8, in <module>
    sys.exit(main())
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 308, in main
    run_tests(args)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 268, in run_tests
    driver = call_get_network_driver(args.vendor)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm/base/clitools/cl_napalm.py", line 170, in call_get_network_driver
    return get_network_driver(vendor)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm/base/__init__.py", line 95, in get_network_driver
    raise e
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm/base/__init__.py", line 86, in get_network_driver
    module = importlib.import_module(module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm_aoscx/__init__.py", line 16, in <module>
    from napalm_aoscx.aoscx import AOSCXDriver
  File "/opt/netbox/venv/lib64/python3.6/site-packages/napalm_aoscx/aoscx.py", line 52, in <module>
    from pyaoscx import session, interface, system, common_ops, port, lldp, mac
ImportError: cannot import name 'system'

Am I missing something here?

I do have the requierements installed, pyaoscx, requests and urllib3 and Python is version 3.6.8 runnign on CentOS Linux release 8.4.2105.

Thanks in advance!

**Comment by alvinc13** [comment]
Hello,
Which version of pyaoscx was installed?  The current version of this driver should be version locked to pyaoscx v1.0.0, as I am still updating the drivers to work with pyaoscx v2.

**Comment by alagoutte** [comment]
> Hello,
> Which version of pyaoscx was installed? The current version of this driver should be version locked to pyaoscx v1.0.0, as I am still updating the drivers to work with pyaoscx v2.

some news about support of pyaoscx v2 ?

**Comment by derekwood08** [comment]
Sorry noob here.  Was successfully able to get 1.0.0 installed but I am now getting the error that reads:  module 'pyaoscx.session' has no attribute 'login'.  The credentials specified as the napalm username and password are the correct creds so im not sure where this lives.  Can someone point me in the right direction?

**Comment by anlx-sw** [comment]
any update about support vor pyaoscx v2? is this repo still maintained?

> Hello, Which version of pyaoscx was installed? The current version of this driver should be version locked to pyaoscx v1.0.0, as I am still updating the drivers to work with pyaoscx v2.

any update about support vor pyaoscx v2? is this repo still maintained?

**Comment by alvinc13** [comment]
Hello, we are still currently waiting on pyaoscx v2 feature parity for NAPALM.  This repo will be updated for v2 once more of the prerequisite modules are released.  We have been working on the release of OSPF and QOS modules for pyaoscx v2 and Ansible, so the development is ongoing, unfortunately it is going slower than expected.

**Comment by anlx-sw** [comment]
Hi, as napalm 3 was released in May 2020 and is widely as  a requirement for lots of other napalm drivers it might be better to release what's already there then to wait for the last features to implemented in pyoscx v2. 

I think there are not too many use cases where the current cx driver is still usable and a napalm 3 driver (or a napalm3 branch of this repo) might be helpful.

**Comment by alvinc13** [comment]
That is a good point.  Due to the delays we have been having, I'll look into creating a NAPALM 3 branch to try and develop that on the side.  Thanks for the suggestion.
